/* eslint-disable */

/**
 * This type was automatically generated by **Yuppi**.
 * _DO NOT MODIFY IT BY HAND_. Instead, modify your Yuppi schema.
 * Use `Yuppi.declare()` to regenerate this type.
 */

export interface User {
  display_name: string;
  username: string;
  email: string;
}
