import { compile, type JSONSchema as JSONSchema2 } from 'json-schema-to-typescript';
import merge from 'lodash.merge';
import fs from 'fs/promises';
import path from 'path';

import { convertToJSONSchema } from './utils/ConvertToJSONSchema.util';
import { convertToYup } from './utils/ConvertToYup.util';
import { pascalCase } from './utils/PascalCase.util';

import { YuppiOptionsDefault } from './defaults/YuppiOptions.default';

import type { AnyObject } from './types/AnyObject.type';
import type { JSONSchema } from './types/JSONSchema.type';
import type { Schema } from './types/Schema.type';
import type { YuppiOptions } from './types/YuppiOptions.type';
import type { YupSchema } from './types/YupSchema.type';

const cleaned_types_dirs = new Set<string>();

export class Yuppi {
  private readonly options: YuppiOptions;

  public constructor(options: YuppiOptions = YuppiOptionsDefault) {
    this.options = merge({}, YuppiOptionsDefault, options);

    void this.cleanupTypesDir();
  }

  private async cleanupTypesDir() {
    const types_dir = path.join(this.options.output_dir ?? './', 'types');

    const exists = async (path: string) => {
      try {
        await fs.access(path, fs.constants.F_OK);

        return true;
      } catch {
        return false;
      }
    };

    if ((await exists(types_dir)) && !cleaned_types_dirs.has(types_dir)) {
      cleaned_types_dirs.add(types_dir);

      await fs.rm(types_dir, { recursive: true, force: true });
      await fs.mkdir(types_dir, { recursive: true });
    }
  }

  public validate(schema: Schema, properties: AnyObject): AnyObject {
    const yup_schema = this.convertToYup(schema);

    return yup_schema.validate(properties, this.options.validate_options);
  }

  public async declare(schema: Schema, name: string) {
    name = pascalCase(name);

    const types_dir = path.join(this.options.output_dir ?? './', 'types');
    const banner_comment = `/* eslint-disable */

/**
 * This type was automatically generated by **Yuppi**.
 * _DO NOT MODIFY IT BY HAND_. Instead, modify your Yuppi schema.
 * Use \`Yuppi.declare()\` to regenerate this type.
 */`;

    const type = await compile(this.convertToJSONSchema(schema) as JSONSchema2, name, { bannerComment: banner_comment });

    await fs.mkdir(types_dir, { recursive: true });

    await fs.writeFile(path.join(types_dir, `${name}.d.ts`), type);
  }

  public convertToYup(schema: Schema): YupSchema {
    return convertToYup(schema, this.options);
  }

  public convertToJSONSchema(schema: Schema): JSONSchema {
    return JSON.parse(JSON.stringify(convertToJSONSchema(schema, this.options))) as JSONSchema;
  }
}
