name: Lockfile

on:
  push:
    branches:
      - '**'

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://registry.npmjs.org

      - name: Delete lockfile
        run: rm -rf ./bun.lock

      - name: Recreate lockfile
        run: bun install

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add ./
            git commit -m "✨ chore: lockfile"
            git push
          else
            echo "No changes."
          fi
