name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create release notes
        run: sed -n "/^## /{ :loop; n; /^## /q; p; b loop; }" ./CHANGELOG.md | sed -z "s/^[[:space:]]*//; s/[[:space:]]*\$//" > ./RELEASE_NOTES.md

      - name: Update release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          body_path: ./RELEASE_NOTES.md
